name: Build One Shot Chapters

on:
  push:
    paths:
      - chapters/side/**
  workflow_dispatch: 


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run Python script
        run: |
          python scripts/one-shot-processor/htmlBuilder.py
        env:
          PYTHONIOENCODING: "utf-8" #

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated changes by GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
