name: Build Website

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 4: Create or modify website files
      - name: Build HTML files
        run: |
          python scripts/main_epub_processor/htmlBuilder.py

      # Step 5: Commit and push modified content to a new branch
      - name: Commit and push website content to a new branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b website
          git rm -rf .  # Remove all files in the branch
          git clean -fd  # Ensure all untracked files are removed
          git add ./website  # Add all modified and newly created files
          git commit -m "Add generated website files"
          git push origin website --force