name: Deploy to Cloudflare Pages

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Publish to Cloudflare Pages
        run: wrangler pages publish ./website --project-name=orv
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}