name: Build Cont Chapters

on:
  push:
    paths:
      - chapters/cont/**
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Convert DOCX
        run: |
          python -m pip install --upgrade pip
          python -m pip install textract==1.5.0
          python scripts/side/docstotxt.py
          python scripts/side/processor.py
          python scripts/side/system-extractor.py
        env:
          PYTHONIOENCODING: "utf-8" #

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Automated changes by GitHub Actions"
          fi
          git pull --rebase origin main || (git stash && git pull --rebase origin main && git stash pop)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-ai:
    needs: run-script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run AI Model
        run: |
          python -m pip install google-genai
          python scripts/side/ai.py
        env:
          PYTHONIOENCODING: "utf-8"
          GEMINI_KEY: ${{ secrets.GENAI_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Automated changes by GitHub Actions"
          fi
          git pull --rebase origin main || (git stash && git pull --rebase origin main && git stash pop)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: run-ai
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 10 seconds
        run: sleep 10
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build Chapters
        run: |
          python scripts/side/system-text-format.py
          python scripts/side/htmlBuilder.py
          python scripts/side/titles.py
        env:
          PYTHONIOENCODING: "utf-8" #

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Automated changes by GitHub Actions"
          fi
          git pull --rebase origin main || (git stash && git pull --rebase origin main && git stash pop)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}