name: Build Website

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 4: Create or modify website files
      - name: Build HTML files
        run: |
          python scripts/main_epub_processor/htmlBuilder.py

      # Step 5: Commit and push modified content to a new branch
      - name: Commit and push website content to the branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ./website  # Add all modified and newly created files
          git commit -m "Update generated website files" || echo "No changes to commit"
          git push origin HEAD

      # Step 6: Deploy the website branch to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: orv
          directory: ./website
