name: Deploy to Cloudflare Pages

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering as well

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes in /chapters directory
        id: check_changes
        run: |
          if git diff --quiet HEAD HEAD~1 -- chapters/; then
            echo "No changes in /chapters directory."
            exit 0
          else
            echo "Changes detected in /chapters directory."
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build Chapters
        run: |
          python scripts/others/sitemap.py
        env:
          PYTHONIOENCODING: "utf-8"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: orv
          directory: website
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Automated changes by GitHub Actions"
          fi
          git pull --rebase origin main || (git stash && git pull --rebase origin main && git stash pop)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
