name: Deploy Minified to Cloudflare Pages

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Minified to Cloudflare Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure deployment only runs on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying from main branch."

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Minification Tools
        run: |
          pip install htmlmin cssmin jsmin jsonmin

      - name: Minify Website Files and Calculate Savings
        run: |
          total_saved=0
          for file in $(find website -type f -name "*.html" -o -name "*.css" -o -name "*.js" -o -name "*.json"); do
            original_size=$(stat -c "%s" "$file")
            python -m htmlmin "$file" --output "$file.min" 2>/dev/null || python -m cssmin "$file" --output "$file.min" 2>/dev/null || python -m jsmin "$file" --output "$file.min" 2>/dev/null || python -m jsonmin "$file" --output "$file.min" 2>/dev/null
            minified_size=$(stat -c "%s" "$file.min")
            saved=$((original_size - minified_size))
            if [ $saved -gt 0 ]; then
              total_saved=$((total_saved + saved))
              mv "$file.min" "$file"
            else
              rm "$file.min"
            fi
          done
          echo "Total space saved: $total_saved bytes"

      - name: Build Chapters (Sitemap)
        run: |
          python scripts/others/sitemap.py
        env:
          PYTHONIOENCODING: "utf-8"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Sitemap Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add website/sitemap.xml # or the path to your sitemap
          if git diff-index --quiet HEAD; then
            echo "No sitemap changes to commit"
          else
            git commit -m "Automated sitemap update by GitHub Actions"
            git pull --rebase origin $(git rev-parse --abbrev-ref HEAD) || (git stash && git pull --rebase origin $(git rev-parse --abbrev-ref HEAD) && git stash pop)
            git push origin $(git rev-parse --abbrev-ref HEAD)
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: orv
          directory: website
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up Minified Changes
        run: |
          git reset --hard HEAD
          git clean -fdx
        if: always()
