name: Manual Reddit Post

on:
  workflow_dispatch:

jobs:
  post_to_reddit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PRAW
        pip install --upgrade pip
        run: pip install praw

      - name: Run Reddit posting script
        env:
          REDDIT_CLIENT_ID: ${{ env.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ env.REDDIT_CLIENT_SECRET }}
          REDDIT_PASSWORD: ${{ env.REDDIT_PASSWORD }}
        run: python scripts/others/reddit.py