name: Manual Reddit Post to Discord (Commit State)

on:
  workflow_dispatch:

jobs:
  post_to_discord:
    runs-on: ubuntu-latest
    # Grant write permissions to the GITHUB_TOKEN for pushing changes
    permissions:
      contents: write # This is crucial for committing back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install praw requests

      # The script automatically creates/reads the file in its own directory
      # No need for separate mkdir here unless the script's path changed.

      - name: Run Reddit to Discord Bot script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          # DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scripts/others/reddit_to_discord.py

      - name: Check for changes and Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add scripts/others/processed_reddit_post_ids.json # Add the specific file
          
          # Check if there are any changes to commit
          if ! git diff --cached --exit-code; then
            git commit -m "chore(bot): Update processed Reddit posts state [skip ci]"
            # Push changes to the current branch
            git push
          else
            echo "No changes to commit for processed_reddit_post_ids.json"
          fi
        # The [skip ci] in the commit message prevents triggering another workflow run
        # if you have workflows set up to run on push.
